# Generated by Django 3.0.5 on 2020-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
