# Generated by Django 3.0.5 on 2020-04-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymSystem', '0004_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('business', models.CharField(choices=[('HIGH END GYM', 'HIGH END'), ('BUDGET GYM', 'BUDGET GYM'), ('BOUTIQUE STUDIO', 'BOUTIQUE STUDIO'), ('MARTIAL ARTS', 'MARTIAL ARTS'), ('OTHER', 'OTHER')], default='HIGH END GYM', max_length=20)),
                ('club', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('managementSoft', models.CharField(max_length=100)),
            ],
        ),
    ]
