# Generated by Django 3.0.5 on 2020-04-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GymSystem', '0006_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user_role',
            new_name='user_gender',
        ),
    ]
