# Generated by Django 3.0.5 on 2020-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymSystem', '0013_auto_20200421_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_image'),
        ),
    ]
