# Generated by Django 3.0.5 on 2020-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymSystem', '0019_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
