# Generated by Django 3.0.5 on 2020-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymSystem', '0020_auto_20200426_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='transformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercise', models.CharField(max_length=50)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('rest', models.CharField(max_length=50)),
            ],
        ),
    ]
