# Generated by Django 3.0.5 on 2020-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymSystem', '0021_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
